name: Build

on:
  push:
    branches: [ master, main ]
    tags: [ '**' ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Generate translation resources
      run: |
        cd translate
        pip install -r requirements.txt
        chmod +x gen_rc.sh po2ymo.py
        mkdir -p generated
        ./gen_rc.sh
      shell: bash

    - name: Restore NuGet packages
      run: |
        Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe
        .\nuget.exe restore AudioPlaybackConnector.sln

    - name: Build x64
      run: msbuild AudioPlaybackConnector.sln -p:Configuration=Release -p:Platform=x64

    - name: Build x86
      run: msbuild AudioPlaybackConnector.sln -p:Configuration=Release -p:Platform=x86

    - name: Upload x64
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: AudioPlaybackConnector64
        path: x64/Release/AudioPlaybackConnector64.exe

    - name: Upload x86
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: AudioPlaybackConnector32
        path: Release/AudioPlaybackConnector32.exe
